In [1]:
import numpy as np

In [2]:
list=[1,2,3,4,5]
list

[1, 2, 3, 4, 5]

#### 1차원 배열 생성하기

In [3]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr=np.array(list)
arr

array([1, 2, 3, 4, 5])

#### 2차원 배열 생성하기

In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

#### 배열의 크기 확인

In [6]:
arr.shape

(5,)

In [7]:
arr2.shape

(2, 3)

#### 배열의 전체 요소 개수 확인하기 

In [8]:
print(arr2.size)

6


In [9]:
#배열타입 확인하기 
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [10]:
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [11]:
#배열 차원 확인하기 
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [12]:
# 3차원 배열을 만들고 배열 크기 , 차원 요소 개수 확인하기
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [13]:
#배열의 크기
arr3.shape

(2, 2, 2)

In [14]:
#배열의 차원
arr3.ndim

3

In [15]:
#배열의 전체 요소 개수 
print(arr3.size)

8


#### 특정한 값으로 배열 생성하기 

In [16]:
# 0으로 초기화 
arr_zeros=np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# 1로 초기화 
arr_ones=np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# 특정한 값으로 채우기
arr_full=np.full((5,5),7)
arr_full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [19]:
#1부터 50이 담긴 배열 생성하기 
arr=np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [20]:
#1부터 50까지 10씩 차이나는 값 배열 생성하기  
arr=np.arange(1,51,10)
arr

array([ 1, 11, 21, 31, 41])

In [21]:
# 타입 지정하여 배열 생성하기 
arr_type=np.array([1.2,2.3,3.4],dtype=np.int64)
arr_type

array([1, 2, 3], dtype=int64)

In [22]:
# 타입 변경하기 
arr_type=arr_type.astype("float64")
arr_type

array([1., 2., 3.])

In [23]:
#타입 확인하기 
arr_type.dtype

dtype('float64')

In [24]:
#랜던값 배열 생성하기 (0과 1사이의 값 생성 )
arr=np.random.rand(2,3)
arr

array([[0.77996523, 0.52568863, 0.39344619],
       [0.79829302, 0.35586762, 0.05722669]])

In [25]:
#두정수사이에 랜던함 정수 발생
arr=np.random.randint(2,10)
arr

8

In [26]:
arr=np.random.randint(2,10,size=(2,3))
arr

array([[6, 4, 6],
       [6, 7, 7]])

#### 배열 연산

In [27]:
# 배열 요소별 연산 
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [28]:
arr+arr

array([2, 4, 6])

In [29]:
arr*arr

array([1, 4, 9])

#### 인덱싱 & 슬라이싱

In [30]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
print(arr[0])

[1 2 3]


In [32]:
print(arr[0][0])

1


#### array 인덱싱

In [33]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# 인덱스 3부터 8이전까지
arr[3:8]

array([3, 4, 5, 6, 7])

In [35]:
# 인덱스 3부터 8이전까지 12를 대입
arr[3:8]=12
arr

array([ 0,  1,  2, 12, 12, 12, 12, 12,  8,  9])

In [36]:
# 0부터 50이전까지 수를 5행 10열로 생성
arr2=np.arange(50).reshape(5,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [37]:
# 2차원 배열 슬라이싱 
# 배열이름[행: 열]
arr2[:2,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [38]:
arr2[:,0]

array([ 0, 10, 20, 30, 40])

In [39]:
arr2[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [40]:
arr2[2,1]

21

In [41]:
arr2[[2,3],[2,3]]

array([22, 33])

In [42]:
name_score=np.array(np.random.randint(50,100,size=8))

In [43]:
name_score

array([90, 51, 60, 71, 79, 64, 79, 55])

In [44]:
name_score >=80

array([ True, False, False, False, False, False, False, False])

In [45]:
name_score[name_score >=80]

array([90])

#### universally 함수

In [46]:
# sum함수
arr=np.random.randint(1,10,size=(4,7))
arr

array([[7, 8, 2, 8, 2, 9, 1],
       [1, 5, 5, 7, 3, 9, 6],
       [3, 5, 6, 4, 4, 6, 1],
       [2, 3, 9, 5, 6, 2, 3]])

In [47]:
print(arr.sum())

132


In [48]:
print(np.sum(arr))

132


In [49]:
#mean()함수
arr=np.random.randint(1,10,size=(4,7))
arr

array([[9, 9, 1, 3, 2, 3, 1],
       [9, 8, 3, 2, 5, 7, 7],
       [4, 4, 2, 4, 1, 4, 5],
       [7, 4, 7, 2, 2, 9, 3]])

In [50]:
print(arr.mean())

4.535714285714286


In [51]:
print(np.mean(arr))

4.535714285714286


In [52]:
#sqrt()함수
arr=np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [53]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [54]:
#abs함수
arr=np.array([-1,2,-3,4,-5])
arr

array([-1,  2, -3,  4, -5])

In [55]:
np.abs(arr)

array([1, 2, 3, 4, 5])

#### 10명에 대한 키와 몸무게가 들어있는 파일을 읽어 bmi지수를 구하시오


In [56]:
data=np.loadtxt("height_weight.txt",delimiter=",")
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [57]:
# 키 
data[0,:]

array([175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
       179. ])

In [58]:
# 몸무게
data[1,:]

array([65.6, 88. , 79.2, 69.3, 55. , 71.2, 73. , 68.9, 74. , 82. ])

In [59]:
bmi= data[1,:]/(data[0,:]*data[0,:])

In [60]:
bmi

array([0.00213715, 0.00270702, 0.00258612, 0.00242065, 0.00160354,
       0.00201449, 0.00231439, 0.00216972, 0.00236203, 0.00255922])